### ISSUE TITLE
Minimal index/search responses

### ISSUE THREAD

**Issue by whoward** [json-api/json-api#87] opened 2013-05-22 07:36 UTC
Hi Everyone,
I just wanted to ask about the response payload of what you'd call the index action in Rails.  I see a lot of talk about sideloading related data into the response which is great but I'm wondering if something should be put into the spec to address the opposite end of this - providing the absolute minimum - the identity of each object

Example:  a `GET` request to `/products` could result in:

```
{
   "products": [13, 59, 25, 99]
}
```

or perhaps

```
{
   "products": [{id: 13}, {id: 59}, {id:25}, {id: 99}]
}
```

With the identifiers of each relevant record returned the client could then retrieve full details using either individual requests to each object url (at `/products/:id`) or in bulk using the collection url (ex. `GET /products?ids=13,59,25,99`)

There are a few advantages I personally see to this approach:
1. The server and client are unburdened in the event the collection contains a very large number of objects.
2. The server is more able to leverage full response caching, as updates to individual objects in the collection would not invalidate the response above (identifiers generally SHOULD be constant unless my expectations are way off)
3. The client is empowered to selectively load the full contents of objects as they see fit, such as paginating or "scroll-loading" depending on their use case.

What do you all think?  Crazy-talk? haha

**Comment by SphtKr** [comment] 2013-05-22 09:50
Somewhat related to #20? See the use-case in [my comment](https://github.com/json-api/json-api/issues/20#issuecomment-18205212).

**Comment by whoward** [comment] 2013-05-22 12:35
They're definitely related and somewhat complimentary.  I think I'd like to emphasize that:
1. The client should be made aware somehow they must perform additional calls to get the full representation (perhaps a meta flag?)
2. specifying the "ids" parameter when fetching the collection url should mandate that full data is returned
3. The server should have the right to project only certain fields by default, it shouldn't be up to the client to select them.

Perhaps taken a step further the server could refuse to include fields on collection urls which would be present on the "self link"

Also perhaps the server could have a standardized response code to indicate too many objects being requested using the bulk fetch.  Example:
 `GET /products?ids=1,2,3,4,5,6,7,8,[...],1000`
could respond with
`HTTP/1.1 413 Request Entity Too Large`

or perhaps `414 Request-URI Too Long` I'm not sure which is best

**Comment by SphtKr** [comment] 2013-05-22 12:59
Not sure about `413`, but I think `414` means something specific: the actual length limitation on the URL string (discussed in #72).

Per your "1.", I mentioned one possible solution in #83, and/or if the client has its data model specifically defined for the resource that would _probably_ suffice. But yes, I'm not sure I have my head wrapped around the implications of more-or-less silently omitted fields, and how the client should figure out that's what's happened.

I'm not sure I agree that "specifying the 'ids' parameter...should mandate that full data is returned", though that's probably a sensible default. The discussion in #20 originally started around dealing with single, large fields (e.g. a binary image--a digital signature also comes to mind), so if you were requesting 1000 objects explicitly (maybe the contents of a folder in an email client), you might kill yourself by requiring all the fields to be included. Dunno though, brainstorming here.

I agree it probably makes sense to allow a server to intelligently include or omit fields that can be lazily requested later. Again that prompts the question of how to communicate to the client that this has happened.

**Comment by steveklabnik** [comment] 2013-05-22 13:45
I need to add more ways to link into part of the spec. Anyway, in the ID style, for example, it'd look just like the example:

``` text
Resource Collections

If the length of an array at a resource key is greater than one, the value represents a list of documents.

{
  "posts": [{
    // an individual post document
  }, {
    // an individual post document
  }]
}

Each document in the list MUST contain an id key.
```

Since the only requirement is `id`, that'd be

``` text
{
  "posts": [{
    {"id":"1"}
  }, {
    {"id":"2"}
  }]
}
```

This, of course, isn't very useful. So you'd need one of two things: either some sort of 'collection relation' where you allow people to query, or self links, which aren't in the spec right now but should be.

This is really a duplicate of #20.

**Closed as completed by steveklabnik** 2013-05-22 13:45 UTC

**Comment by andrewsardone** [comment] 2013-06-06 19:46
> self links, which aren't in the spec right now but should be.

These `self` links, would they take the form of an `href` key in the attributes section, a la, the [response body of a document creation request](http://jsonapi.org/format/#url-based-json-api)?

**Comment by steveklabnik** [comment] 2013-06-06 22:57
They would be a `self` key in the `links` section.
