### ISSUE TITLE
To-Many Relationships and authorization

### ISSUE THREAD

**Issue by RSSchermer** [json-api/json-api#316] opened 2014-11-15 12:50 UTC
I recently came across jsonapi.org and this got me very excited. One thing that puzzles me though, is the preferred way of authorization for to-many relationships, where the parent object determines whether the client is authorized to read or write objects to the collection of child objects (for individual child objects the child object id can be used for authorization of course, the issue is only with collections of child objects where only the parent id is available for authorization).

Example to make it easier to explain: suppose I'm building a simple task manager application where i have a User model and a Task model. The User has many Tasks. A client acting on behalf of a User is only authorized to read this User's Tasks (not those of other Users) and may only create new Tasks for this user (not for other Users). With all requests, the client includes token for authentication where the token can be used to identify the User the client acts for.

The first issue is with reading the Tasks that belong to the a User. In my understanding there are 2 general approaches for reading a relationship (not including 'linked' side loading). The first involves first obtaining a list of ids of Tasks that belong to a User and then making a `GET` request to `/tasks/first_task_id,second_task_id,third_task_id,...`, which I'll call the id-list method. The second consists of using the 'links' semantic and making a `GET` request to `/users/user_id/links/tasks`, which I'll call the links method.
It seems to me that the links method would be preferable in the context of authorization, because I believe that the error semantics are simpler and more clear. If I make a request to `/users/user_id/links/tasks` and I get a `403 Forbidden` response, this means to me: I am not allowed to read the tasks of this user. It arguably does not need an error message to explains this in more detail. If i make a request to `/tasks/first_task_id,second_task_id,third_task_id` and I get a `403 Forbidden` response, this is much more ambiguous to me. In the links method I viewed it as a request for a single collection resource, and even though strictly speaking this is also a single collection resource with a compound key, intuitively for me, this id-list method is a request for multiple individual resources in a single request. My mind doesn't process this as "I'm not allowed to read the collection resource `/tasks/first_task_id,second_task_id,third_task_id`", but as "I'm not allowed to read one or more of `/tasks/first_task_id`, `/tasks/second_task_id`, `/tasks/third_task_id`". For the id-list method, I would have to add an error message to tell me exactly which of the tasks I'm trying to read is causing this `403 Forbidden` response. Conceptually, authorization and the links method seems much clearer than authorization and the id-list method.

The second issue is with creating a new Task for a user. It seems to me that there may be 2 approaches that the current spec allows. The first would be to use a 2-step approach. One would make the following request:

``` json
POST /tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": {
    "description": "Some task"
  }
}
```

The API responds with the created resource. The client uses the created resource's id and makes a second request:

``` json
POST /users/user_id/links/tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": "task_id"
}
```

For this to work though, I would have to remove the "presence" validation on the Task's User property. If the client fails to make the second request, I may end up with Tasks in my DB that don't belong to any user. I'd prefer not to remove my "presence" validation.
I'm actually not sure that the spec allows this second approach, but let's assume that it does. The client would make the following request:

``` json
POST /tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": {
    "description": "Some task",
    "links": {
      "user": "user_id"
    }
  }
}
```

It seems to me that authorization would now involve validating the `task.links.user` property (which I guess would deserialize to the 'task.user_id' property). This feels like mixing authorization with validation (and would in e.g. Rails probably be most easily handled through adding a custom validation, instead of doing controller 'action-based' authorization). I would rather not mix validation with authorization.
The approach that seems most intuitive to me, isn't actually currently allowed by the spec as I understand it. The client would make the following request:

``` json
POST /users/user_id/links/tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": {
    "description": "Some task",
  }
}
```

I wont have to remove my "presence" validation and I'm also able to do 'action-based' authorization without any mixing of validation and authorization logic. However, the current spec states: "A to-many relationship MAY be added by sending a POST request with a single resource ID to the URL of the relationship." It does not mention anywhere that posting a resource object to a links URL is allowed, so I take it that this approach is not allowed and that instead approach 1 needs to be followed.

As mentioned, there's no issue with updating, or deleting Tasks, or reading an individual Task, because in these cases the Task's id can be used for authorization, akin to "shallow routing".

I dont think "to-many relationships with authorization" is a very uncommon use case. I may have completely missed the point somewhere here. What would be the preferred way to handle authorization and to-many relationships with jsonapi?

**Comment by hesalx** [comment] 2014-11-15 14:16
> A client acting on behalf of a User is only authorized to read this User's Tasks (not those of other Users) and may only create new Tasks for this user (not for other Users).
> 
> The first issue is with reading the Tasks that belong to the a User. In my understanding there are 2 general approaches for reading a relationship (not including 'linked' side loading).

REST resources are not severely restricted to be defined by URL only. A response may relies on a bunch of factors, like session, headers, API token etc.

If there are no cross-user management, you are free to use simple URLs to access user-related resources.
`GET /tasks` would list the current user's tasks
`POST /tasks` would create a new task for the current user (`user_id` not needed)
The same requests without the authorized user would fail with `401`.

> The second issue is with creating a new Task for a user. It seems to me that there may be 2 approaches that the current spec allows. The first would be to use a 2-step approach. 

The first is definitely wrong way to create a resource for the reasons you have described.

> I'm actually not sure that the spec allows this second approach

If you allow some user to manage the other user's tasks, you are right about the `"links"`. There is [the example for updating](http://jsonapi.org/format/#crud-updating-relationships). Creating and updating should be generally the same, I think. The spec is under development, PRs with more obvious examples would be welcome.
Relations with `not null` constraint are so common that, in any case, there should be the way to create a resource with relations included.

There is the proposal #311 which would make such requests much more clear and obvious:

``` javascript
POST /tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": {
    "description": "Do the job",
    "user": "1"
  }
}
```

> The approach that seems most intuitive to me, isn't actually currently allowed by the spec as I understand it. 

Yes. It's kinda best practice of REST to update and create resources on their primary URLs rather than alternative ones. 
`POST /users/user_id/links/tasks` is more likely about updating the user than creating a task, but actually it's about **creating a relation**. Because the same could be done with `POST /tasks/task_id/links/users`, which is likely to update the task, but actually doesn't.

In the case of many-to-many relation there is a separate collection with `(user_id, task_id)` pairs. That's it! `/users/user_id/links/tasks` is not pointing to a part of `/tasks` collection, but to the relations collection. So when you `POST /users/user_id/links/tasks` you can only _create a new relation_ but not the resources behind it.

**Comment by hesalx** [comment] 2014-11-15 15:13
I'm sorry, but there may be some great misunderstood.

There are two kinds of relations: many-to-one and many-to-many. Because of the same prefix it was omitted in the spec. one-to-one is just the particular case of many-to-one.
"to-many" from the spec could be confused with the widely used term "one-to-many"

many-to-one is the relation where `user_id` is a property of a task itself, and the many-to-many is where  a join table with `(user_id, task_id)` pairs exists, so task can have many users.

You are using singular `user` as attribute name.
**Can a task have many users in your case?** If not it's to-one relation. I would suggest you not use the relationship URL at all and set the `user` attribute for a task directly on creating and updating.

If it's truly many-to-many relation, I was mistakenly took the example of many-to-one in the middle part of my answer, but this doesn't change the approach. Here is [the many-to-many example](http://jsonapi.org/format/#crud-updating-to-many-relationships) which shows that you're definetly should be allowed to create a resource with initially set to-many relations:

``` javscript
POST /tasks
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "tasks": {
    "description": "Do the job",
    "links": {
      "users": [ "1" ]
    }
  }
}
```

Anyway, `"links"` **where not forbidden** by the spec for `POST` requests.

**Comment by RSSchermer** [comment] 2014-11-15 15:29
> REST resources are not severely restricted to be defined by URL only. A response may relies on a bunch of factors, like session, headers, API token etc.

I know this is possible, but it has always been my understanding that it is considered good practice to make an URL identifying the a resource (entity or entity collection) at a certain point in time, return the same resource for all clients. Except some clients may get a 401 response, some a 403 and some a 200. That may be a misconception on my part though. I guess it's jsonapi.org's stance that it is perfectly fine to return different response bodies for the same URL based on the session?

> Can a task have many users in your case? If not it's to-one relation. I would suggest you not use the relationship URL at all and set the user attribute for a task directly on creating and updating.

The example was meant as a one-to-many relationship. I guess the advice would be to go with the approach that mixes authorization with validation for one-to-many relationships? I mean I guess if the related model is the user itself as in this simple example you could leave out the user_id entirely in the post body as you say and use the user_id related to the session. In a slightly more complex example though, where the Tasks dont belong to a User but belong to a Department and a User can only add tasks to a Department he belongs to, this does not really work anymore.

I'm just trying to find out what the best approach would be and what approach will be supported by client side implementations such as EmberData.

**Comment by hesalx** [comment] 2014-11-15 18:24
I've got the point. 

> As mentioned, there's no issue with updating, or deleting Tasks, or reading an individual Task, because in these cases the Task's id can be used for authorization, akin to "shallow routing".
> 
> I dont think "to-many relationships with authorization" is a very uncommon use case. I may have completely missed the point somewhere here. What would be the preferred way to handle authorization and to-many relationships with jsonapi?

JSON API is media type. It's not about authorization at all.

Your authorization mechanism depends on request. The more appropriate way is to authorize models, regardless of the request existence. Your way prescribes some requests structure, e.g. `POST` entire resource to relationship URL, which conflicts with the API spec. 

The API spec is quite consistent therein. `POST`, `PUT` and `DELETE` to relationship URL will affect only the relationship. 
Other cases are dangerous. `POST` a resource may ends up with a conflict in URL's and body's relationship id(s). `POST /something/:id/user` would create a user if one isn't set before! And, finally, what should `DELETE` do? Accidentally destroy the actual user instead of unassign the one from the task?
The spec prevents all this.

You are likely to change the way your server processes requests, if you want to follow the spec consistency.

**Comment by RSSchermer** [comment] 2014-11-15 19:13
I get that JSON API is not about authorization. If I were to use JSON API though, there are valid use cases where I need authorization right? My point is that the JSON API spec does not seem to allow doing authorization, without mixing validation and authorization logic.

I get model based validation, it's essentially what I mean with action/route/URL based validation. Can the client access model A (at `/models/A`)? 
Yes: 200 Ok with model. 
No: 403 Forbidden. 

But that does not quite work with `POST` create with relationships. Can the user `POST` this task to `/tasks`?

``` json
{
  "tasks": {
    "description": "Some task",
    "user": "378"
  }
}
```

Yes, because the auth token belongs to user 378: 201 Created with created model. 
No, because the auth token does not belong to user 378: I dont know?
Maybe 400 Bad request:

``` json
{
  "validation_errors": {
    "user": ["not authorized to reference this user."]
  }
}
```

Or maybe 403 Forbidden:

``` json
{
  "message": "You are not authorized to create this resource with this user property."
}
```

I'm not really sure what's best, because I'm not sure if I'm doing validation or authorization here. It's getting mixed up and I don't see a way around it. I'd prefer it if I could somehow do this without mixing these concerns. The way I used to do this: the URL/route/action is something that needs to be authorized, the payload is something that needs to be validated. However, the API structure that JSON API prescribes precludes this.

So in fact JSON API does to a certain extend prescribe how to do authorization, even if it is not technically part of the spec. Now, this may be a necessary evil: there may be no good way to do authorization without sacrificing other important things. I just was hoping that there was a good way to do this that had not occurred to me.

**Comment by hesalx** [comment] 2014-11-15 23:55
Just throw out the `user` from `POST` requests. Forbid it, ignores it, whatever. Just take away the cause of your problem. Your problem is caused by ambiguity.
- Does the user only allowed to access the owned tasks?
  - Throw away the `user` attribute at all.
- Does the user may read other's tasks, but create only own?
  - Throw away the `user` attribute from the `POST`. It's the current user a priori. Ignore any extra attributes in the request, or return `400 Bad request`, the `user` would be one of them.
  - `PUT` and `DELETE` already has the `user` in the URL. The authorization way, you are used to, does work. `403 Forbidden` for alien users if definitely correct.

> In a slightly more complex example though, where the Tasks dont belong to a User but belong to a Department and a User can only add tasks to a Department he belongs to, this does not really work anymore.

The same paragraphs as for users case above. Just the current department will be used instead of the current user. 

More complicated?
- Does tasks belong to a user **and** a department?
  - Throw away the `departments` attribute at all. It's the current department a priori, no other ones are allowed anyway. `400 Bad request` if it's present.
  - Does the requested user **not** belongs to the department?
    - `404 Not Found`. The relationship user doesn't exist in department. Pretty clear if department is already known http://jsonapi.org/format/#crud-updating-responses

And so on...
JSON API doesn't force you to make all the attributes updatable or creatable (it's insane).
Just forbid any ambiguity with `400 Bad request`.
Just reject unambiguous but unauthorized requests with `403 Forbidden`.
Just fail unambiguous requests with unknown relationships with `404 Not Found`.

> I know this is possible, but it has always been my understanding that it is considered good practice to make an URL identifying the a resource (entity or entity collection) at a certain point in time, return the same resource for all clients. 

Consistency is the good practice. 
In your case an URL generally **will not** return the same **for all clients** . It will return `403` for any client expect authorized for the URL.
Anyway, it **will return the same** for all the clients **authorized with the same user**. Either `200`, `403` or whatever it should, but the same with the same user.
You may not use `user_id` at all and it doesn't change the above behaviour.

If there's no cross-user management, make the API shared by the user scope.
If there's no cross-department management, make the API shared by the department scope.

The majority cloud services are behave like that. They don't share the entire hierarchy all over the world. The API works inside your scope (company, account, department, user or whatever), if changing the scope inside the session is impossible.

**Comment by ahacking** [comment] 2014-11-16 02:37
I would examine carefully your domain model as it seems there are some concepts not reflected in your models. For instance you mention clients which have a distrinct role and access control rule but there is no client model. I would have thought you would have use cases for clients to review and manage tasks they have assigned. If you have a client model then perhaps they have tasks they own?

Perhaps your tasks need to include the concept of owner and assignee? Perhaps more than one user is applicable for a task? If so consider TaskRole eg owner/assignee/manager etc ...  depending on the workflows and use cases you are trying to solve. I'm just reading between the lines based on what you have described as some things appear to be missing from your model.

As per what @arantir has already said the scoping of a resource is not just the URL, authorisation headers can also play a part to scope things differently. Also remember http allows resources to be overlapping  so don't get too hung up on canonical endpoints for everything as that doesn't always work well for the different facets that you need to deal with.

I believe once you have the domain model sorted and your access controls expressed clearly the REST will follow.

**Comment by RSSchermer** [comment] 2014-11-16 09:15
@ahacking the client is not a model. It is for example a javascript client. It acts on behalf of a resource owner as per e.g. the OAuth 2 spec. In this domain model, the resource owner is represented by the User model.

@arantir I think you misunderstand. This is not my domain model. This is just an example to illustrate a point. And as mentioned, disallowing the user property in a POST payload body, only works in this simple use case. I'll give you an actual domain model for an application I'm working on where this does not work.

I'm building an physician activity scheduler. A Physician has-and-belongs-to-many Practices. A Practice has-many Activities. A Physician has-many Activities (an Activity always has a Practice, and depending on whether it also has a Physician, it is considered an assigned or unassigned Activity). A Physician may create new Activities for Practices he belongs to. I assure you that this is a perfectly valid domain model and an accurate reflection of reality (albeit slightly simplified here of course).

So what happens here? Can the Physician (client acting on behalf of the Physician) create this unassigned Activity?

``` js
POST /activities
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "activities": {
    // Other activity properties
    "practice": "32"
  }
}
```

Yes, because the Physician is a member of Practice 32: 201 Create with created Activity.
No, because the Physician is not a member of Practice 32: I dont know?
Maybe 400 Bad request:

``` json
{
  "validation_errors": {
    "practice": ["not authorized to reference this practice."]
  }
}
```

Or maybe 403 Forbidden:

``` json
{
  "message": "You are not authorized to create this resource with this practice property."
}
```

It basically the exact same example of course. I do believe this is a more fundamental issue than a misconceived domain model.

What I think it comes down to is the somewhat odd approach taken with regards to shallow nesting in JSON API.

Example 1: Parent _one-to-many_ Child.
`GET /parents/1/links/children`: returns a list of the Children that belong to Parent 1.
But this is not allowed:

``` js
POST /parents/1/links/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "children": {
    // other child properties
    "parent": "1"
  }
}
```

Example 2: Parent _many-to-many_ Child == Parent _one-to-many_ JoinObject _many-to-one_ Child
`GET /parents/1/links/children`: returns a list of the Children that belong to Parent 1, not a list of JoinObjects that belong to Parent 1.
But here I'm allowed to post a JoinObject:

``` json
POST /parents/1/links/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "children": "1"
}
```

Which is actually conceptually equivalent to (just different syntactically):

``` json
POST /parents/1/links/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "join_objects": {
    "child": "1"
  }
}
```

And this makes total sense, because `links/children` actually represents the JoinObjects and not the Children. The odd thing here is actually the way `GET /parents/1/links/children` works, because technically it should really return a list of JoinObjects if it is to be consistent with the way it works for one-to-many relationships.

I'm basically making an argument for shallow nesting. I know there is a general sense that shallow nesting is evil in the Ember community (although I've never read an explanation of why, just that it's evil) and presumably there is here as well. Actually though, the current way `/links` works is definitely a partial and, as I was hopefully able to explain above, a slightly weird implementation of shallow nesting: 
- It allows shallow nesting for `GET` requests for any relationship type.
- It allows shallow nesting for `POST` requests for JoinObjects for the many-to-many relationship type.

It's just scoped on a `links` segment in the URL. What imho is not a good thing is this inconsistency:
- If `GET /parents/1/links/children` returns a list of children for a one-to-many relationship, then it should return a list of JoinObjects for a many-to-many relationship.
- I'd like to be able to post to any relationship: why is this difference between JoinObjects and normal objects introduced when it comes to creation? I know some ORMs (Entity Framework, ActiveRecord, Hibernate) tend to make some distinction, but RDBMS's certainly don't and lower level implementations such as Scala Slick don't either.

I think what I would propose is this:
- `links` is reserved for many-to-many relationships:
  - `GET /parents/1/links/children` is only allowed if Parent many-to-many Children. It returns a list of children, not JoinObjects.
  - `POST /parents/1/links/children` is only allowed if Parent many-to-many Children. It creates a new JoinObject.
- Shallow nesting is allowed:
  - `GET /parents/1/children` is only allowed if Parent one-to-many or one-to-one Children. It returns a list of children.
  - `POST /parents/1/children` is only allowed if Parent one-to-many or one-to-one Children. It creates a new Child.
  - `GET/PUT/DELETE /parents/1/children/1` is never allowed. This should be `GET/PUT/DELETE /children/1`

This does allow you to retrieve the actual children of a many-to-many relationship directly, instead of JoinObjects, which would be very impractical. It also eliminates the inconsistency in the way it works for one-to-many vs many-to-many as there is an actual syntactical distinction (it's fine that it works differently, because it looks differently).

What makes shallow nesting so evil? Is there something fundamental or is it just difficult to implement in EmberData? I think the synergy with authorization is at least one pro for shallow nesting, what are the cons?

All this discussion about whether or not I have a valid domain model is muddying the waters. Should I turn this into a new issue?

**Comment by ahacking** [comment] 2014-11-16 13:07
OK I miss understood what you meant by 'client acting on behalf of a user', it sounded like there were first class concepts not reflected in your models.

There is much discussion going on in various issues which you may be able to contribute to if you are fine ding json-api unable to meet your use case.

I'm not a maintainer of json-api and I haven't been able to use it for many use cases which is why I have been actively participating in the discussion to hopefully move it forward.

I don't have time right now to go through all your questions or statements but my current feeling is json-api goes too far in some areas. That view isn't shared by everyone however.  I guess I look to HTTP and what it says a resource is and I should be able to PUT multiple resource representations if I can GET them. I should be able to scope to some subset of attributes on multiple sib resources and bulk update them. I should be able to this through a nested endpoint if I need to (not that I do this in my apps) but it fits with HTTP.

I am not certain json-api is prohibiting a lot of things though, it uses SHOULD a lot which doesn't mean MUST NOT.

I use Ember and have embedded objects in a few areas but they are not resources with endpoints of their own but I have to normalize them into separate models for Ember Data and use the EmbeddedRecordsMixin in my serializers. Json-api is not specific to ember so its probably best to keep a clear separation of concerns and just focus on json-api here.

It might also help if you can specifically reference the document sections in json-api you believe are prohibiting your use of json-api  or sections which are problematic for your use cases. I'm not sure based on a cursory read of your message where the exact difficulties in the spec are but it seems you have interpreted something in thr spec that is not aligning with what you are trying to do. Eg I don't know what part of the spec rules something is 'evil' as you say.

**Comment by hesalx** [comment] 2014-11-16 13:23
@RSSchermer I knew it wasn't your real model, and my latter example is still suitable for your real model... But, never mind...

It took me some time to insight into your idea. You're very welcome to get acquainted with #317 and live you comments.

**Comment by RSSchermer** [comment] 2014-11-16 13:48
I completely agree that EmberData should not be a concern at all. This is an API spec, the primary concerns should be server side concerns (such as ease of authorization). Client side implementability should definitely be a concern, but completely secondary to any server side concerns. I do get a sense reading the spec though that it is quite EmberData driven. EmberData definately existed first and from looking at the commit history, large initial parts of this spec are written by Ember core members. My point was more that Ember's concerns shouldn't restrict this spec (in other words: I completely agree with you @ahacking).

I guess I took the lack of description of shallowly nested resources without the `/links` thing (in combination with my knowledge of the dislike for them from the Ember community) as an indication that this is not something that you are supposed to do. And actually I'm pretty sure that this is the intend of the current spec: it describes so much in such detail, that such a major thing such as nested resources for expressing relationships missing out, must surely be an indication that according to the spec, it should not be done. And as explained, what `/links` currently describes, is kinda but not really nested resources, with some oddities.

@arantir Thanks very much for creating #317! It looks very interesting and I guess we'll continue the discussion there. About my real model and your last solution: I still don't see it quite working. I think the thing that trips it up is the many-to-many relationship between Physicians and Practices. If a Physician belongs to 3 Practices and I leave out the `"practice"` property for a new unassigned Activity out of the payload, then I have no way to determine which of the 3 Practices it should be assigned to. Although there is a concept of a 'current Physician' (through the auth token), there is no concept of a 'current Practice'.

EDIT: I did learn that I should try to simplify an example and just use the actual use case. The risk you end up missing some crucial point is kinda big.

**Comment by lgebhardt** [comment] 2014-11-16 14:32
@RSSchermer, If I'm reading your concern correctly, you're looking to the spec to determine which response code is most appropriate for an associated record. I don't think the spec should have an opinion on whether you return 403 Forbidden vs 404 Not Found vs 400 Bad Request. All could be appropriate depending on the requirements of your system.

For example if you don't want to expose even the existence of a resource at a particular id then returning the same code for all errors where the resource doesn't exist or the user isn't permitted to see it would be appropriate. 

In other cases you may want to distinguish between a resource that is forbidden vs one that doesn't exist. 

As @arantir says you do not need to allow every attribute to be createable or updateable on a resource. These can certainly come from the session.

**Comment by hesalx** [comment] 2014-11-16 14:41
@RSSchermer There nothing to discuss more in this issue, main problem should be migrated to #317, but just to make some things clear:
I was talking about the latter example where the `"user"` is a legal part of the payload for all requests, as your `"practice"` is too. Therefore no `400  Bad Request` needed, you may use `403 Forbidden` seemly.

But your proposal just makes total sense for some other cases, whereas makes your own case more clear.
E.g. `404 Not Found` for `POST /parents/1/children` should clearly means inexistence of `parent/1` regardless of the payload. Because any payload processing errors, if the payload is valid itself, are to be rejected with `422 Unprocessable Entity`.
The same with `403 Forbidden`. A server may respond with `403` in a great bunch of conditions. But it makes things much clear if `403` is related to the URL and HTTP method only. So I really understand your aspiration to achieve this behaviour and so #317 would allow this.

**Comment by RSSchermer** [comment] 2014-11-16 14:51
@lgebhardt I would summarize my concerns as follows:
- Inconsistency in `/links` behavior for one-to-many vs many-to-many relationships.
- An unclear line between validation and authorization forced by the current spec.

I understand the freedom in what http response to return, but my example of the 400 and 403 was merely illustrate the second point. The current spec does not seem to allow proper shallow nesting, which creates a somewhat messy situation when it comes to authorization. I would prefer URL/route/action based authorization be possible (instead of validation based authorization), both for clarity in API responses (you don't really even need explanatory error messages for 403 responses with URL/route/action based authorization), as well as because the frameworks and libraries I have worked with seem to consider this the preferred way (ASP MVC action annotations, Symfony firewall, Rails + cancan/authority before filters).

**Comment by lgebhardt** [comment] 2014-11-16 15:49
@RSSchermer I'm not sure the spec should require exposing the linking table (JoinObject) in a simple many to many relationship. If you need to expose the JoinObjects, for example to have additional properties on the JoinObject, wouldn't those simply be another resource with the relationship as a one to many? Making the JoinObject a full resource solves the ambiguity, does it not? And for simple many-to-many relationships the client shouldn't necessarily need to know about the join objects/linking tables. 

As far as validation vs authorization, I'm not seeing where the spec is unclear. Can you provide some more details?

**Comment by RSSchermer** [comment] 2014-11-16 16:22
@lgebhardt I was not proposing to expose the JoinObjects at all. I was merely pointing out that POST works differently for a one-to-many relationship as opposed to a many-to-many relationship. My proposal at the end of https://github.com/json-api/json-api/issues/316#issuecomment-63211458 merely suggests making this difference between the way one-to-many and many-to-many relationships work explicit. It also suggests the introduction of shallow nesting for normal one-to-one and one-to-many relationships and allowing the POSTing of new resources to nested collections directly. I agree completely that exposing the JoinObjects would be pointless. If it needs to be exposed (because extra attributes are defined on the JoinObject) then it should indeed be a full resource.

As to validation and authorization: it is not that the spec is unclear. In fact the spec is quite clear on how to add to relationship collections. The point is that what the spec describes does not allow for clear separation between validation and authorization, when it comes to adding a resource to a nested collection. A cleaned up version of the example:

The use case: a physician activity scheduler. A Physician has-and-belongs-to-many Practices. A Practice has-many Activities. A Physician has-many Activities (an Activity always has a Practice, and depending on whether it also has a Physician, it is considered an assigned or unassigned Activity). A Physician may create new Activities for Practices he belongs to.

The way it would work without shallow nesting:
A Physician (client application acting on behalf of the physician) want to add an unassigned Activity to Practice 1:

``` js
POST /activities
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "activities": {
    // Other activity properties
    "practice": "1"
  }
}
```

However, the Physician does not belong to Practice 1, so he is not authorized to do this. To verify if the Physician is authorized, properties of the payload need to be analysed. I would consider this validation and the easiest way to do this in e.g. Rails, is through adding a custom validator. It's sort of unclear if we are doing validation or authorization. I think the preferred response would probably be:

``` json
400 - Bad request
{
  "validation_errors": {
    "practice": ["not authorized to reference this practice."]
  }
}
```

Which is the typical format I use for validation errors.

This is how it would work with shallow nesting:

``` js
POST /practices/1/activities
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "activities": {
    // Other activity properties
  }
}
```

Now authorization does not depend on payload parameters, I can use the URL/route/action for authorization. This seems to fit much better with the common authorization paradigms (ASP MVC action annotations, Symfony firewall, Rails + cancan/authority before filters). Also this would be the response:

```
403 - Forbidden
```

I'd say that arguably no error message is necessary. The API response is simpler and clearer. The server implementation is simpler and more standard. As I understand the spec though, this is not currently allowed.

Now, this example is based on my earlier suggestion at the end of https://github.com/json-api/json-api/issues/316#issuecomment-63211458 for consistency with what I wrote earlier in this thread. @arantir May have a superior proposal in #317 though, that preserves the `/links` segment in all relationship URLs.

**Comment by lgebhardt** [comment] 2014-11-16 16:48
@RSSchermer Thanks. Now I understand where you are coming from.

In your example, using shallow nesting, you would potentially still have some attributes that would be subject to validation and not authorization. For example maybe an admin can create an Activity and assign it to both a Physician and a Practice. What route would you use in this case? There are many more situations where you couldn't rely on the shallow nesting entirely for authorization concerns.

What I'm going to be doing in my code is authorizing all the related resources which are passed in before the request ever reaches the validation stage. Thus in your example I wouldn't return a validation error, but rather a 403 or 404 error.

**Comment by RSSchermer** [comment] 2014-11-16 16:53
@lgebhardt The point is more that authorization depends on the 'current user' and the 'parent resource', in pretty much all cases of to-many relationships. In the nesting approach, neither the current user, nor the parent resource are part of the payload (current user is determined by the auth token, parent resource is determined by the route). This allows for nice separation of authorization (route and auth header) and validation (payload), and clean responses.

EDIT: 

> For example maybe an admin can create an Activity and assign it to both a Physician and a Practice.

Ah I see what you mean, sorry it didn't really click straight away. That is actually a valid concern. I guess it's solved differently in my actual implementation and that gets lost in the simplified example. In the actual implementation a Practice actually has many Physicians through Memberships (and vice versa: a Physician has many Practices through Memberships). An Activity actually belongs to Practice (always) and belongs to Membership (optionally: assigned/unassigned). It belongs to a Physician through the Membership. The example I gave earlier (`POST /practices/1/activities`) would still be the way for creating unassigned Activities. For creating an assigned Activity directly the request would be:

``` js
POST /memberships/11/activities
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "activities": {
    // Other activity properties
  }
}
```

So I guess in my implementation this is not an issue. However, I guess in a more general sense you have a very valid point. I'd say that it would still be nice to have shallow nesting to solve the majority of cases though (or allow a Memberships solution like this).

**Comment by attitude** [comment] 2015-01-13 13:25
Not sure whether this was ever proposed, so I post it here. Please correct me if anything.

I'm thinking how to distinguish representation of relations of same-to-same type when there's difference of meaning in parent-child relationship. This edge case comes up only when objects of the same type are being linked, e.g. categories: category has parent category and can have children categories.

I have strong opinion on these links are being mixed right now according the specs without having the _link type_ different. I mean users linked under `authors` attribute under `post.links`. This approach is useful, since user can be linked also as `owner`, `editor` implying meaning of a link.

You could create `category.links.parentCategories` and `category.links.childCategories` to distinguish same-to-same relations. Yet it does not self-describes which set of links is considered as the objects object being linked to, or objects being linked to the object if you omit the `parent`, `child` prefixes. You can only sense it because you as a human being understand the words.

I'm pretty sure it would break/breaks the specs, but here's the thing:
1. Let's call to-many relationships as `linked` (object has linked objects)
2. Let's call to-one relationships as `links` (object links to objects)

Example response to `GET /collections/android-phones`" (for simplicity and relation dependency, the id's are _unique_ texts here):

``` json
{
  "links": {
    "collections": "http://example.com//collections/{collections.id"
  },
  "collections": {
    "id": "android-phones",
    "name": "Collection of Android phones",
    "links": {
      "collections": ["phones"]
    },
    "linked": {
      "collections": ["samsung-android-phones", "sony-android-phones", "other-android-phones"]
    }
  }
}
```

The top level would still use `links` attribute as proposed by specs, only the results would distinguish between the parent and child links using `links` and `linked` attributes.

Note: The meaning could be swapped as well for `object has links` and `object is being linked to`. It's a matter of agreement on specs.

**Comment by tkellen** [comment] 2015-06-29 11:41
In the future, discussions like this would be _fantastic_ for http://discuss.jsonapi.org. For now, I'm giving this a close. JSON API has reached 1.0 and we cannot make backwards incompatible changes.

**Closed as completed by tkellen** 2015-06-29 11:41 UTC
Labels: enhancement
