### ISSUE TITLE
Should resource ID match resource endpoint URL?

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#490] opened 2015-03-18 04:21 UTC
Does JSON API make any recommendations about a resource endpoint having an ID that matches the endpoint URL? For example, if I have a person resource with a primary key 'id' and a `name` attribute guaranteed to be unique, MAY my resource be accessible at `/people/somename`? SHOULD it?

**Comment by steveklabnik** [comment] 2015-03-18 13:31
The only thing we have related to URL design is a recommendation: http://jsonapi.org/recommendations/#urls

The spec places no requirements on the structure of your URLs.

**Comment by steveklabnik** [comment] 2015-03-18 13:31
(closing this since it's not a bug, but we can still keep talking about your case if you'd like)

**Closed as completed by steveklabnik** 2015-03-18 13:31 UTC

**Comment by jfinkels** [comment] 2015-03-18 15:34
That answers my question: the specification makes no recommendations of the style about which I asked. Thanks.
