### ISSUE TITLE
Querying Relationships

### ISSUE THREAD

**Issue by richmolj** [json-api/json-api#1175] opened 2017-05-30 13:35 UTC
I'd like the spec to support querying relationships (or at least provide recommendations for querying relationships). Here's the current state of relationship querying:

| Query Type  | Status |
| ------------- | ------------- |
| Sparse Fieldsets | Complete |
| Sorting | Recommendation |
| Pagination | None |
| Filtering | None |

I went ahead and made relationships fully queryable as part of [jsonapi-suite](jsonapi-suite.github.io/jsonapi_suite). From that experience, here are my suggestions to get full "relationship querying" in the spec itself:

### Pagination

Namespace the normal pagination query parameter with the corresponding `type`, e.g.:

> /posts?include=comments&page[comments][size]=3

Should fetch the post and 3 comments.

### Filtering

Suggest a recommendation that filters prefixed with the relationship `type` filter the corresponding relationship:

> /posts?include=comments&filter[comments][active]=true

### Sorting

This is already in the spec as a recommendation, just putting here for completeness. The sort parameter should be dot-prefixed with the `type`, e.g.:

> /posts?include=comments&sort=-comments.created_at

I'd prefer this become more than just a recommendation, but that would still satisfy me.

### Sparse Fieldsets

This is already in the base spec, just putting here for completeness. Fieldsets prefixed with `type` should limit fields on the corresponding resource:

> /posts?include=comments&fields[comments]=text,rating

I can break these up if needed, just wanted to get the conversation going.

**Comment by jamesplease** [comment] 2017-05-30 15:15
I think your table is a bit misleading. I would say that the spec covers all of those things, and is flexible in the areas where you have put "None."

Your table says that the spec does not cover paginating included resources, but that is not accurate. From the spec:

> To paginate an included collection returned in a compound document, supply pagination links in the corresponding links object.

So, the spec clearly supports this. You then get to decide how you want to use the `page` query parameters.

Similarly for filtering, you get to decide how you want to use that query parameter. Because filtering by included resources isn't against what's in the spec, then it is spec compliant, and therefore the spec supports it.

---

I think what you're getting at here is some more examples for these things, rather than simply support for them (which is how your post begins):

> I'd like the spec to support...

I agree that examples are definitely important, don't get me wrong. And perhaps there's more room for the spec to elaborate on some of these situations, but the spec _does_ support these things.

**Comment by richmolj** [comment] 2017-05-30 15:30
@jmeas pagination links do not support the use case I am talking about. I would like to execute the query "give me the post, and three most recent comments". You cannot do this with pagination links.

The filter suggestion is of course spec-compliant. I'd argue this is not good enough. Library authors, on both the client and server, are not implementing this functionality because the spec says nothing about it. I'd like to see JSONAPI eventually become a true GraphQL competitor - this will not happen without some way to filter relationships. As I said, I am happy with this being a recommendation or extension rather than the base spec...we just need **something**.

By "support" I don't mean we have to say "this is the only way to do this". But I'd like something a bit more than just examples...a recommendation or extension would suit me. I'd also mention the spec is already making a recommendation for sorting and sparse fieldsets, my intent is to simply be more comprehensive.

**Comment by dgeb** [comment] 2017-07-26 22:01
> I'd like to see JSONAPI eventually become a true GraphQL competitor - this will not happen without some way to filter relationships. As I said, I am happy with this being a recommendation or extension rather than the base spec...we just need something.

I agree. Again, we will need to allow extensions to specify filtering in more fine grained detail than is specified in the base spec. In fact, I would like most of our recommendations to basically become "recommended extensions" which more formally and rigorously enforce a usage contract.

**Comment by morgs32** [comment] 2018-06-15 19:58
Anyone have or seen a good example of this?

**Comment by richmolj** [comment] 2018-06-15 20:30
@morgs32 [JSONAPI Suite](https://jsonapi-suite.github.io/jsonapi_suite/) currently supports deeply nested reads and writes (with extensions to the spec like this).

**Comment by remmeier** [comment] 2018-06-16 04:03
note that when it comes to filtering of relationships, there are two different use cases:

1. filtering of relationships requested through inclusions
2. filtering of the requested root resource based on an attributute of a related resource

examples for both should be provided. We make use of basically the same thing for 1 (filter[comments][active]) and use the dot operator for 2 (filter[comments.active]=active). For the later there is additionally the issue of multi-valued relationships, so an operator might be necessary like [EXISTS] or [ALL] to decide whether all items must match, or only a single one, or something else. But so far we did not use this.

**Comment by remmeier** [comment] 2018-06-29 09:21
how should we proceed with this issue? I could do an initial PR for a new extension?

To some degree I think we may need two extensions in the future:

1. a basic one along the line of the current recommendation, e.g. filter[name]=...
2. a more advanced one, e.g. filter=name EQ ... AND ...

For for a first step having 1. would already be great.

**Comment by jelhan** [comment] 2022-02-17 22:55
This seems to be a duplicate of #1001

**Comment by jelhan** [comment] 2023-12-07 08:02
Let's consolidate the discussion in #1001. I'm closing this one as a duplicate.

**Closed as completed by jelhan** 2023-12-07 08:02 UTC
Labels: profile
