### ISSUE TITLE
Top-level links and nullable pagination contradiction and possible incorrect jsonschema

### ISSUE THREAD

**Issue by Ilyes512** [json-api/json-api#1512] opened 2020-09-15 22:40 UTC
The spec says that top-level links can either be a string containing the link's URL or be an object:

> Each member of a links object is a “link”. A link **MUST** be represented as either:
> 
> - a string containing the link’s URL.
> - an object (“link object”) which can contain the following members:
>     - href: a string containing the link’s URL.
>     - meta: a meta object containing non-standard meta-information about the link.

Source: https://jsonapi.org/format/#document-links

While in the pagination section it says:

> The following keys **MUST** be used for pagination links:
> 
> - `first`: the first page of data
> - `last`: the last page of data
> - `prev`: the previous page of data
> - `next`: the next page of data
> 
> Keys **MUST** either be omitted or have a null value to indicate that a particular link is unavailable.

The jsonschema spec currently does not allow pagination links that contain a null. For example: https://www.jsonschemavalidator.net/s/gtFfYMI8

(In the above jsonapi schema I edited the top level oneOf rule so it only tries to validate against a "success" document so it outputs only the relevant errors).

The cursor-pagination also suggest setting the pagination links to the value of null in some cases. See https://jsonapi.org/profiles/ethanresnick/cursor-pagination/

So there is a contradiction between the Links section and the Pagination section; and if setting null values should indeed be allowed, then the current schema is invalid.

So I am not sure how to continue...

Edit:

I see that this issue was already mentioned... almost **5 years** ago! It's however part of the JSON-API 1.2 milestone: https://github.com/json-api/json-api/milestone/3 But I don't see this fixed any time soon :(

Relevant issues:
  - https://github.com/json-api/json-api/issues/887
  - https://github.com/manyminds/api2go/pull/313

**Comment by Relequestual** [comment] 2021-03-31 10:43
I'm going to address this issue as part of a new issue relating to updating the JSON Schema to validate v1.0 responses.
There are some issues with the data in the demo/playground link, which I will address as part of that issue.

**Comment by Relequestual** [comment] 2021-03-31 12:34
Suggest closing in favour of #887

**Comment by jelhan** [comment] 2022-02-01 21:17
Closing this one as a duplicate of #887.

**Closed as completed by jelhan** 2022-02-01 21:17 UTC
