### ISSUE TITLE
Sideposting: use of `included`; interactions with `?include`

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1215] opened 2017-08-30 20:56 UTC
I wanted to pull a few of checklist items from #1197 that related to `?include`/`included` out into a separate thread, since that one was getting pretty crowded and these questions seemed severable. The result of this discussion can then be used to update the checklist in #1197. In particular, this issue is for the items:

- [ ] Should sideposted resources [in the request document] be within the included member or within some new ad-hoc member?
- [ ] Should created sideposted resources in the response be within the included member or within some other ad-hoc member?
- [ ] What should happen if a client uses ?include on their POST and (for some reason) doesn't list in that param all the relationship paths for which they sideposted resources?

My current thinking on this is: 

- Sideposted resources should go in `included`, in both the request and response documents. What are the arguments against this at this point? I know I initially used a member called `embedded` but I'm not sure that ever really made sense.

- Any sideposted resources should always be included in the response regardless of the value of the `?include` parameter. Letting the `?include` parameter exclude newly sideposted resources just seems to add way more complexity than it's worth. (See discussion [here](https://github.com/json-api/json-api/pull/1197#user-content-include-param).)

**Comment by beauby** [comment] 2017-08-30 23:08
Regarding
> Any sideposted resources should always be included in the response regardless of the value of the ?include parameter. Letting the ?include parameter exclude newly sideposted resources just seems to add way more complexity than it's worth. (See discussion here.)

The issue is that the current spec states:
> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

Hence, having a separate top level member for 1. sideposting resources and 2. returning created related resources makes sense to me.

**Comment by ethanresnick** [comment] 2017-08-31 02:17
> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

But why not just relax that requirement to include sideposted resources regardless? That seems like it's backwards-compatible, because no existing implementations will be sideposting resources, and it saves implementation complexity.

**Comment by beauby** [comment] 2017-08-31 02:52
That's definitely a possibility. The tradeoff here seems to be:
1. either introducing a new top level member and have clearer semantics for the `included` member (when sideposting, the new member would always be present in the response, containing the created sideposted resources),
2. or not introducing a new top level member and having the client distinguish between included resources and created sideposted resources (most probably by presence of a `tempid`).

I would favor the former but I'm not sure I fully understand the added implementation complexity you're referring to.

**Comment by ethanresnick** [comment] 2017-09-01 20:07
Gotcha. I don't have strong, immediate feelings either way. 

The implementation complexity only happens if we put the sideposted resources in `included` and then let the `?include` param exclude them, so that concern isn't relevant to either of the options you mentioned per se, so long as we adjust the `?include` rules appropriately.

Thinking out loud a bit: 

- having a new, separate member keeps the semantics of `included` simpler, and it keeps the relationship between `included` and `?include` more direct. I wonder, though: could a resource object be duplicated between `included` and this new top-level member? I.e., does `POST /articles?include=comments` with a side-posted comment lead to the side-posted comment showing up in both `included` and the new member, or is the document de-duped? If it's de-duped, then which member "wins" (i.e., gets to hold the side-posted resource)? Neither option seems great—if `included` wins, the client has to look there for sideposted resources anyway; if the new member wins, it makes the semantics of `included` much muddier—so maybe the right course would be to just allow the duplication? 

- I could live with some duplication, but I want to understand a little better first just how big of a problem it is for the client to have to filter `included` by those that have a temp ID in order to find the side-posted resources. It seems like the client will likely be processing `included` already—though I guess it's not too hard to imagine cases where it wants to defer that processing but needs the side-posted resources more immediately.

**Comment by beauby** [comment] 2017-09-01 21:04
Duplication seems like the way to go, as those are separate concerns, and
any de-duping would break the semantic gains.

**Comment by ethanresnick** [comment] 2017-09-02 01:34
I agree that duplication would seem to make more sense here/seem to be necessary to get the benefits of having a separate top-level member. My one concern with duplication, though, is that it seems inconsistent with the current spec; namely, we say:

> A compound document MUST NOT include more than one resource object for each type and id pair.

If I recall correctly, @dgeb was behind that text in the base spec, so I'd like him to weigh in on the rationale behind it and on whether duplication would be ok here.

The rationale stated in the spec is that:

> This approach ensures that a single canonical resource object is returned with each response, even when the same resource is referenced multiple times.

But, if that's the whole goal, I wonder if the same thing could be accomplished with a requirement that says: if a resource object with the same (type, id) shows up multiple times in a document, it must be identical everywhere it occurs. If so, we could apply that restriction to address possible duplication between `included` and side-posted resources, and possibly update the compound document duplication restriction to be consistent with that.

Also, as a small aside: looking at that text with fresh eyes, I'm noticing that it doesn't actually totally, 100% forbid all duplication in a document; specifically, because it only applies to compound documents, it seems like it's possible for primary data to contain the same resource object twice in a non-compound document (even if that's unlikely and would be odd conceptually). I'm not sure if/how that bares on this conversation.

**Comment by beauby** [comment] 2017-09-02 15:26
Regarding the duplication restriction applying only to compound documents, I am convinced it is an oversight (the same way the current wording of the full-linkage clause allows a compound document with a null/empty primary `data`, and a 2-cycle in `included`).

An other possibility that has not been mentioned would be to have all side-posted resources within the primary data. This is conceptually a bit odd, but technically feasible (possibly with the first resource(s) of the primary data having a special status). I'm not necessarily advocating for this, but thought it was worth mentioning.

**Comment by ethanresnick** [comment] 2017-09-03 07:14
> Regarding the duplication restriction applying only to compound documents, I am convinced it is an oversight 

Yeah, I'm sure that's an oversight too. I was just pointing it out in case the fact that that edge case was already allowed in 1.0 (even if by oversight) effects our thinking here. It may not.

> An other possibility that has not been mentioned would be to have all side-posted resources within the primary data. This is conceptually a bit odd, but technically feasible (possibly with the first resource(s) of the primary data having a special status). 

Yeah, I was thinking about this too, and I've come around to the idea more and more. 

If we view `data` on a POST/PATCH request as meaning "here's the graph of resources I want to create/change", then I think this does make sense conceptually, and it has the advantage that it would let us leverage the existing de-duplication rule (i.e., a `?include=`d resource that's already in `data` doesn't show up in `included`). 

It also keeps a clear separation between "the resources I sent" and "the extra resources I asked for" without having to add a new top-level member that might prove inappropriately-named for future use cases. (For instance, if we called the new top-level member `sideposted`, but then we also wanted to allow updates of related resources down the line, that could be weird; with this approach, we'd just put the related resource's updates in `data` too.)

I also like that this approach seems to lead naturally to the possibility of bulk creations/updates  (since `data` is already an array). IMO, APIs that support sideposting are likely to want to support bulk creation/updating too (it's low marginal effort), so that's nice.

**Comment by beauby** [comment] 2017-09-03 17:03
I agree with all points. Only caveat is that conceptually, I wouldn't want the spec to allow for an endpoint to accept sideposting requests with just anything (like `POST`ing an `article` along with `comments` on a `/users` endpoint for instance). This was implicitly discouraged by keeping only the primary data in `data`.

**Comment by ethanresnick** [comment] 2017-09-05 17:54
> Only caveat is that conceptually, I wouldn't want the spec to allow for an endpoint to accept sideposting requests with just anything (like POSTing an article along with comments on a /users endpoint for instance). This was implicitly discouraged by keeping only the primary data in data.

Yeah, I kinda see what you're saying about how putting everything in `data` maybe makes misuse a little more likely. I think keeping the full-linkage requirement will prevent the most egregious cases, though. Beyond that, I don't think the spec should try to stop implementations that want to do bizarre/unadvisable things from doing those things—mostly because that's going to be impossible given that URIs are opaque to the spec. Like, even under today's spec, it's already possible for an API to support `POST`ing an `article` to `/users`, to use your example; I don't think now allowing attached comments too makes that much worse.

**Comment by beauby** [comment] 2017-09-05 18:53
@ethanresnick Fair point. In that case, should we add a statement about ordering of the sideposted resources within `data`?

**Comment by ethanresnick** [comment] 2017-09-05 19:26
@beauby What kind of statement were you thinking? Would the ordering effect the semantics, or just be a convention to improve readability?

**Comment by beauby** [comment] 2017-09-05 21:20
@ethanresnick Not sure actually, I just thought it might become of use in the future, in which case we might want to either 1. prevent the servers from giving meaning to the ordering or 2. force a specific ordering.

**Comment by ethanresnick** [comment] 2017-09-15 22:54
So, I've been thinking a bit more about the idea of reusing `data` to hold the sideposted resources, and I see two issues:

1. What do we do at relationship endpoints, where data would normally be resource identifiers and the sideposted content would be full resources? I.e., having heterogeneous `data` like this seems weird:

    ```js
   PATCH /articles/1/relationships/tags

    { 
      "data": [
         { "type": "tags", "id": "1" }, 
         { "tempid": "2" }, 
         { "type": "tags", "tempid": "2", "attributes": { /* ... */ }, "relationships": { /* ... */ } }
      ]
    }
    ```

2. Using `data` blurs the distinction between which resources are sideposted and which are "primary data". Instead, it's essentially saying that the whole graph is the primary data.  I don't think this is necessarily a problem, but it does mean that, in the sideposting case, we'd have to relax the restriction you (i.e., @beauby) quoted in 1216:

    > A server MUST return 409 Conflict when processing a POST request in which the resource object’s type is not among the type(s) that constitute the collection represented by the endpoint.

I'm not sure if either of these issues are dealbreakers, but they're worth pointing out. The first issue bothers me more than the second, I think. Re the second: requiring users to split up the resources between two members doesn't seem to really limit the overall power of each endpoint (if the concern is around god-like endpoints), and servers can always partition the resources in `data` by type if they decide they need to view some as primary and some as sideposted.

**Comment by ethanresnick** [comment] 2017-10-12 20:20
@dgeb Please weigh in here. Also, ping @beauby in case you have any thoughts on the above.

**Comment by dgeb** [comment] 2017-11-22 23:54
Sorry for sitting on the sidelines for so long in this discussion.

I don't think that it's an absolute requirement that sideposting return a representation of every resource that's been sideposted in the response document.

If `include` has been specified, then that should dictate the contents of `included` in the response (in accordance with the current spec).

If `include` has not been specified, then it is up to the server to return what it wants in `included` in the response (also in accordance with the current spec).

**Comment by ethanresnick** [comment] 2017-11-24 00:35
Ok, so it sounds like we should go with putting the sideposted resources in `included`, in both the request and response documents, allowing the `?include` parameter's value to exclude some sideposted resources in the response. Servers that don't want to support the complexity of figuring out which sideposted resources to send back have the option of not supporting `?include` on a POST. 

This approach saves us from having to introduce + agree on the name for a new top-level member, which I think is big, and from having to relax the no duplication requirement. The tradeoff is that the client will have to loop through `included` to find the sideposted resources, but they're probably doing that anyway.

I do think we should say though that, on a sidepost, when `?include` is not present, the server **must** include the sideposted resources by default.

Does this sound good to y'all? If so, @beauby, can you please update your PR? Maybe we can finally get it merged soon :)

**Comment by jelhan** [comment] 2023-04-19 19:09
I created an bulk create extension addressing this use case: https://github.com/jelhan/json-api-bulk-create-extension Happy to receive feedback, questions and suggestions as GitHub issues on those repository.

I assume that we want to gather real-world experience before promoting any extension (and profile) as official extension/profile. And that we don't want to add support for it in base spec as it could be well solved using an extension. Going to close this issue.

**Closed as completed by jelhan** 2023-04-19 19:09 UTC
Labels: extension
