### ISSUE TITLE
Guidance for links to empty relationships

### ISSUE THREAD

**Issue by nwjsmith** [json-api/json-api#386] opened 2015-03-02 16:25 UTC
The spec currently gives guidance on how to structure relationships when the exist, but gives no guidance for when they do not.

It is obvious (but not stated in the spec) that when the value of a relationship is a related resource URL, it should be `null` when missing:

**Present**

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "comments": {
      "resource": "http://example.com/articles/1/comments"
    }
  }
}
// ...
```

**Empty**

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "comments": {
      "resource": null
    }
  }
}
// ...
```

Things are less clear when a relationship is provided as a link object because of the `self` link. Even when the related resource is empty, the `self` link is a valid link for modifying the relationship.

**Present**

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author",
      "resource": "http://example.com/articles/1/author",
      "type": "people",
      "id": "9"
    }
  }
}
// ...
```

What does this look like if the `author` relationship is empty? There are two strategies: omitting keys, or `null` values.

**Missing, omitting keys**

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author"
    }
  }
}
// ...
```

**Missing, `null` values**

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author",
      "resource": "http://example.com/articles/1/author",
      "type": null,
      "id": null
    }
  }
}
// ...
```

I propose that the `null` value approach be taken by the spec. @dgeb work on PR https://github.com/json-api/json-api/pull/357 might help to inform where we go on this?

**Comment by bintoro** [comment] 2015-03-02 18:24
To signify an empty to-one relationship, you're supposed to set `id: null`. If it's a to-many relationship, you say `ids: []`. If you normally use `data`, I guess you could have an empty array in there, too.

@ethanresnick reinitiated the discussion on unifying `id`, `ids`, and `data` in #312, which, if realized, would simplify this system.

~~If you only use URLs, then I'd say you'd set `resource: null`. A URL doesn't signal cardinality anyway, so this is fine.~~ Actually, a _related resource URL_ is supposed to remain unchanged even if it doesn't point to a physical resource, so no, `resource` cannot be `null`. If present, it must be a URL.

I mean, if you remove all items from a collection that represents a to-many relationship, the URL will still work and return an empty array. Clearly, the same should be true for to-one relationships as well.

If my proposal in [#379](https://github.com/json-api/json-api/issues/379#issuecomment-76602572) is implemented, you would put `null` in the _canonical URL_ slot to indicate that the relationship is empty. This applies to both to-one and to-many relationships.

**Comment by nwjsmith** [comment] 2015-03-03 16:16
@bintoro good catch on the related resource URLs. I've updated the example.

**Comment by steveklabnik** [comment] 2015-03-05 01:30
This is a duplicate of https://github.com/json-api/json-api/issues/348, I think

**Closed as completed by steveklabnik** 2015-03-05 01:30 UTC

**Comment by RyanPridgeon** [comment] 2019-01-25 12:31
If anyone else stumbles upon this and is still confused because the original question isn't answered;

[This part of the JSON API spec seems to imply that links can be present without any target resources.](https://jsonapi.org/format/#document-resource-object-related-resource-links)

> If present, a related resource link MUST reference a valid URL, even if the relationship isn’t currently associated with any target resources. 

From this I believe the following are valid;

```
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": null
    }
  },
```

```
  "relationships": {
    "authors": {
      "links": {
        "self": "http://example.com/articles/1/relationships/authors",
        "related": "http://example.com/articles/1/authors"
      },
      "data": []
    }
  },
```
