### ISSUE TITLE
What is meant by "unsupported request"?

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1274] opened 2018-05-03 11:49 UTC
According to the spec:

> A server MAY return 403 Forbidden in response to an unsupported request to create a resource.

> *[Section "Updating Resources"*] A server MUST return 403 Forbidden in response to an unsupported request to update a resource or relationship.

> *[Section "Updating To-Many Relationships"]* A server MUST return 403 Forbidden in response to an unsupported request to update a relationship.

What is meant by "unsupported request" in these cases? Some immediate interpretations that come to mind are:
* The operation (creating/updating) is not allowed at all - in this case, a better response would be 405 Method Not Allowed, see #1273 
* The request included fields that are read-only - seems to overlap with the following:
   > A server MAY return 409 Conflict when processing a PATCH request to update a resource if that update would violate other server-enforced constraints (such as a uniqueness constraint on a property other than id).
* The request included attribute values that are not allowed - also seems to conflict with 409, see point above

In general then, I find myself wondering in which cases I should return 403 and 409, not to mention other codes entirely such as 405 and 422. Could anyone shed some light on this?

**Comment by ethanresnick** [comment] 2018-05-03 21:59
I agree that this term is under-defined. Perhaps we can clarify it in the future, but my advice for now would be to use 405 where appropriate (though probably avoid 422, as the spec tends to prefer 400 instead). As you may have noticed, each section on allowed responses ends with:

> A server MAY respond with other HTTP status codes.
> ...
> A server MUST prepare responses, and a client MUST interpret responses, in accordance with HTTP semantics.

To me, that leaves the door open to using 405.

**Comment by cmeeren** [comment] 2018-05-04 06:11
My interpretation of

> A server MAY respond with other HTTP status codes.

is that the server may respond with other status codes *as long as it does not conflict with other MUSTs*. In this case, I interpret the spec to say that if e.g. the response to update a resource is "unsupported" (whatever that means), the server MUST return 403, but when the request is not "unsupported" (and does not fall into other responses specified with MUST), other status codes can be used.

Is my interpretation incorrect? Did I perhaps misunderstand you?

**Comment by ethanresnick** [comment] 2018-05-05 22:29
> My interpretation... is that the server may respond with other status codes as long as it does not conflict with other MUSTs

Yes, that interpretation's correct. But, because "unsupported" is undefined, *and* another MUST is about following HTTP semantics, I'd say that, if your server doesn't support the method at all, you can safely return 405. Again, we may clarify unsupported later, but I wouldn't worry about following HTTP in the mean time; the intention certainly isn't to make that impossible.

**Comment by cmeeren** [comment] 2018-05-06 08:45
Thanks for the clarification!

**Comment by jelhan** [comment] 2022-03-26 08:05
Closing this as a duplicate of #1548. #1548 is newer but got more attention.

**Closed as completed by jelhan** 2022-03-26 08:05 UTC
