### ISSUE TITLE
Including related resources in CRUD requests

### ISSUE THREAD

**Issue by ksimka** [json-api/json-api#562] opened 2015-04-20 11:11 UTC
Can we include related resources in a response to a CRUD operation?

Example: users can create posts, posts can be liked by users, like is a resource too. User A has post P, user B likes P creating a new like L. But creating a like causes an increment of "liked_num" field of a post. So in order to reduce the number of requests we want to return a new version of P with created L in a single response.

Should it looks like this?

`POST /likes?include=post`

``` js
{
    "data": {
        "id": 100,
        "type": "like",
        "user_a_id": 3,
        // ...
        "links": {
            "post": {
                "linkage": {"id": 50, "type": "post"}
            }
        }
    },
    "included": [
        {
            "id": 50,
            "type": "post",
            // ...
            "likes_num": 42 
        }
    ]
}
```

If yes, can someone please add an example of such response to the CRUD section of the spec?

**Comment by gr0uch** [comment] 2015-04-20 11:22
Sure, why not? I think that anything that is not forbidden in the spec should be allowed.

**Comment by outerim** [comment] 2015-04-22 22:59
Depending on your interpretation I think this could be forbidden by the spec as it stands right now. For instance:
http://jsonapi.org/format/#crud-creating-responses-409

> A server MUST return 409 Conflict when processing a POST request in which the resource's type does not match the server's endpoint.

A request like that could easily be seen as a request to create a resource with a different type than the endpoint to which the request was directed.

That said, I actually have a pressing need for this use case. That is, to transactionally create a resource and dependent resources. Rather than build some sort of transactional semantics on top of HTTP and make multiple requests I think the spec (or an extension thereof) should support this in some form. I've done some preliminary investigation here and the biggest issue I see is that without making client generated ids mandatory there seems to be no good way of specifying linked objects (because linkage has to specify the type and id of a member.) We briefly looked at allowing the client to use a generated ID in linkage and included but have the server respond with the actual created id in the response.

For now we are waiting to see if any official solution emerges but would be happy to contribute if someone is working on something.

**Comment by bintoro** [comment] 2015-04-22 23:11
I think this is a duplicate of #205.

**Comment by dgeb** [comment] 2015-04-23 03:25
Closing as a duplicate. Please continue conversation on #205 and perhaps #536

**Comment by ksimka** [comment] 2015-04-23 07:03
@dgeb I've looked at that issues and I think it's another case. We don't need to **create related** resources or **link existing** ones. We want to **respond with some related** resource that was **changed** too. It's like instant notification to a client, what's happened during request.

Btw, I've just recalled a working example of that kind of design: in twitter, when you retweet, you immediatly get a new number of retweets and favourites. In terms of resources: you create a new resource "retweet", and in a response you get that created resource and a related resource "counter" that holds a number of retweets and that has just been updated with the same request.

Correct me please if I'm missing some point.

**Comment by bintoro** [comment] 2015-04-23 07:38
@ksimka You're right, the issue you raised is actually not a dupe of #205. Sorry! I responded to @outerim's comment, which talks about creating multiple interlinked resources at once.

As for the original question here, I think it's a good one, and I find the use of the `include` parameter in this way a bit problematic. I would expect `POST /likes?include=post` to mean that the `post` resource is to be created alongside the `like`. That is, I would expect `fields` and `include` in POST/PATCH/PUT requests to describe the _input_, not the output as with GET.

However, the use case presented here is valid. Perhaps we could specify that `fields` and `include` are meant for customizing response documents only and come up with another way of delineating target resources for create/update operations. (Even though not needed in the base spec, this capability is going to be necessary for sideposting and PUT implementations.)

**Comment by dgeb** [comment] 2015-04-24 11:38
Ok - reopening for further discussion.

**Comment by dgeb** [comment] 2015-04-24 11:50
Here's what the spec says:

> An endpoint MAY return resources related to the primary data by default.
> 
> An endpoint MAY also support custom inclusion of related resources based upon an include request parameter. This parameter MUST specify the relationship using the name used in the links section of the primary data.
> 
> If a client supplies an include parameter, the server MUST NOT include other resource objects in the included section of the compound document.

I believe it's fine for a server to include related resources in response to a CRUD operation. It also seems fine to specify `include` or `field` (or even `sort` for bulk ops) params that target the response (not request) document. Furthermore, if the `include` param is included, the server MUST NOT include other resource objects.

In short, I don't see anything wrong with applying the params from fetching to CRUD ops. However, the spec should be more explicit about this. In particular, it should be clarified that these params only apply to response documents.

**Comment by ksimka** [comment] 2015-04-24 12:01
> In short, I don't see anything wrong with applying the params from fetching to CRUD ops. However, the spec should be more explicit about this. In particular, it should be clarified that these params only apply to response documents.

Absolutely agree. That's exactly what I wanted to say :) Thanks!

**Comment by hhware** [comment] 2015-04-26 23:16
Wouldn't it make sense to introduce the notion of default `include` into the spec, perhaps as a recommendation for implementations? A given endpoint could have different default values of `include` for different HTTP methods. 

Related: 
- https://github.com/json-api/json-api/issues/536#issuecomment-95368335
- https://github.com/hhware/json-api/commit/978d3f10d6ab5662f42a0bba8a8850e5bbfc4cbb

**Comment by tkellen** [comment] 2015-05-20 19:08
@hhware I think we've already introduced that?

> An endpoint MAY return resources related to the primary data by default.
> 
> An endpoint MAY also support an include request parameter to allow the client to customize which related resources should be returned.
> 
> If an endpoint does not support the include parameter, it must respond with 400 Bad Request to any requests that include it.
> 
> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include other resource objects in the included section of the compound document.

**Closed as completed** 2015-05-21 13:33 UTC
