### ISSUE TITLE
Grouping included member by relationship

### ISSUE THREAD

**Issue by stevenpslade** [json-api/json-api#1164] opened 2017-05-08 22:56 UTC
As per fetching includes (http://jsonapi.org/format/#fetching-includes):

It would be nice if the included member data for relationships was grouped by relationship id.

So rather than an array of items and having to parse each item and checking the relationship, it would be grouped by common relationship type and id.

The current format makes it tedious to parse the included data and check each item's relationship and then sort. Is there a reason the included member is this way?

**Comment by jamesplease** [comment] 2017-05-08 23:51
Is this a dupe of https://github.com/json-api/json-api/issues/1144 ?

**Comment by stevenpslade** [comment] 2017-05-09 00:28
I don't think so. I'm wondering why included could not be grouped like this:

```
"included": {
    "author": {
        "foo_relationship_id_1": {
           "1": { ...}
         },
         "foo_relationship__id_2": {
           "76": { ...}
         }
    }
}
```
This way you could get included[type][relationship_id][ids] and then all the item's ids with that relationship. Currently, say in JS on the client, you have to parse each item's included[relationships][type][data][id] and group it from there.

Unless this is intended. All the necessary data is definitely available. So if it is intended that the client groups the request data then my suggestion is not needed.

**Comment by jamesplease** [comment] 2017-05-09 04:32
The reason is that the included array does not contain dupes, yet it must return all of the related items. Consider a person resource that has two relationships: friend and mother. These are also person resources. Imagine that for one particular person, the mother and friend relations are one person. The best way to return this is in an array where the type and ID of that person are included.

The cons of this are that you must do the lookup yourself, as you've pointed out, but it keeps the payload as small as possible.

What would returning a mother and friend that are the same ID in your system look like? Would the included resource be duplicated since it appears in two relationships?

**Comment by stevenpslade** [comment] 2017-05-09 06:53
Thank you. This makes a lot of sense and I understand now why it is like this. I really appreciate you taking the time to explain the reasoning.

**Closed as completed** 2017-05-09 06:54 UTC
