### ISSUE TITLE
Errors with dynamic data representing the offending pieces

### ISSUE THREAD

**Issue by krainboltgreene** [json-api/json-api#294] opened 2014-10-20 13:32 UTC
So lets say you have a rich client for making blog posts.

In the creation of a blog post it asks you for tags, as it's early 2006 and tags are new and cool.

You type in: "programming", "fiddles", and "poop".

The rich client sends the request and the server validation layer says "Nope! Can't have tags named poop, not allowed!"

How does the server tell the client which tag is offending? None of the current specification for errors has anything like this.

**Comment by dzrw** [comment] 2014-11-04 04:54
A recent alternative to the errors object, "Problem Details for HTTP APIs" (#307) [addresses](https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00#section-3) this use-case by defining an `instance` property which is a URI that identifies the specific occurrence of the problem (e.g. http://example.com/tags/poop).

**Comment by krainboltgreene** [comment] 2014-11-04 04:56
How is the client supposed to use such a URI?

**Comment by dzrw** [comment] 2014-11-04 04:58
A rich client would understand that the errors object is a special thing to be handled specially, so it may combine that URI with its knowledge of what it's trying to do (e.g. create tags) to highlight the invalid tag.

Granted, tags ought to be resources.

**Comment by dzrw** [comment] 2014-11-04 05:20
Disregard, #307 was closed as a duplicate.

**Comment by ahacking** [comment] 2014-11-04 06:03
@politician Thats still not useful as I even if I could somehow identify the problem as a particular name field on a particular resource and say 'You must have a name',  I can't at the same time say "you forgot to provide your email address', and by the way, "the password you used is too short".  Again its a draft spec that doesn't solve real world problems because it can't handle multiple problems or even provide addressability of where the problem lies to any useful level of granularity.

Json api is aligned with json-pointer which is useful for pointing at the problem bits of json, whilst that draft you seem to like only says `instance`, which is not particularly meaningful or useful for clients to process.

**Comment by ahacking** [comment] 2014-11-04 09:36
I have asked some rather direct questions w.r.t the htttp-problems draft over at mnot/I-D#74 given the lack of applicability the draft has to basic api and client error/problem processing needs.

Hopefully there will be some fruitful discussion which results in a more useful specification.

**Comment by krainboltgreene** [comment] 2014-11-04 09:56
For clarification, here's what my JSONAPI implementation returns:

``` json
{
  "errors": [
    {
      "id": "email_not_present",
      "context": null
    },
    {
      "id": "email_does_not_match",
      "context": {
        "pattern": "(?-mix:^[^@\\s]+@([^@\\s]+\\.)+[^@\\s]+$)"
      }
    },
    {
      "id": "name_not_present",
      "context": null
    },
    {
      "id": "password_not_present",
      "context": null
    },
    {
      "id": "password_was_out_of_range",
      "context": {
        "maximum": 1024,
        "minimum": 8
      }
    },
    {
      "id": "signature_not_present",
      "context": null
    },
    {
      "id": "signature_was_out_of_range",
      "context": {
        "maximum": 64,
        "minimum": 2
      }
    },
    {
      "id": "username_does_not_match",
      "context": {
        "pattern": "(?-mix:^\\S*$)"
      }
    },
    {
      "id": "username_was_out_of_range",
      "context": {
        "maximum": 64,
        "minimum": 2
      }
    },
    {
      "id": "username_not_present",
      "context": null
    }
  ],
  "meta": {},
  "links": {},
  "linked": {}
}
```

**Comment by steveklabnik** [comment] 2015-03-05 00:36
I believe this is a duplicate of https://github.com/json-api/json-api/issues/206

**Closed as completed by steveklabnik** 2015-03-05 00:36 UTC
